-- Create Junctions Table
create table junctions (
  id bigint generated by default as identity primary key,
  name text not null,
  location text, -- Legacy: "lat,long" or description (deprecated, use latitude/longitude)
  latitude float, -- Decimal degrees (e.g., 51.5055)
  longitude float, -- Decimal degrees (e.g., -0.0158)
  video_source text not null, -- URL or RTSP link
  status text default 'active', -- 'active', 'offline', 'maintenance'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Traffic Logs Table (Time Series Data)
create table traffic_logs (
  id bigint generated by default as identity primary key,
  junction_id bigint references junctions(id) not null,
  vehicle_count int default 0,
  congestion_level text, -- 'Low', 'Medium', 'High'
  avg_speed float,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Violations Table (Events)
create table violations (
  id bigint generated by default as identity primary key,
  junction_id bigint references junctions(id) not null,
  violation_type text not null, -- 'Red Light', 'Wrong Way', 'Speeding'
  image_url text, -- URL to snapshot in Supabase Storage
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) - Optional for now, but good practice
alter table junctions enable row level security;
alter table traffic_logs enable row level security;
alter table violations enable row level security;

-- Create policies (Allow public access for development)
-- SELECT policies
create policy "Public junctions are viewable by everyone." on junctions for select using (true);
create policy "Public traffic_logs are viewable by everyone." on traffic_logs for select using (true);
create policy "Public violations are viewable by everyone." on violations for select using (true);

-- UPDATE policies (required for worker to update junction info)
create policy "Allow public updates on junctions" on junctions for update using (true) with check (true);

-- INSERT policies (required for worker to log data)
create policy "Allow public inserts on junctions" on junctions for insert with check (true);
create policy "Allow public inserts on traffic_logs" on traffic_logs for insert with check (true);
create policy "Allow public inserts on violations" on violations for insert with check (true);

-- Mock Data for Junctions
insert into junctions (name, location, video_source, status)
values 
('Main St & 5th', '40.7128,-74.0060', 'assets/Videos/sample2.mp4', 'active'),
('Broadway & 42nd', '40.7580,-73.9855', 'assets/Videos/sample.mp4', 'active');
